apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: blue
  labels:
    name: app
    app: go
    color: blue
spec:
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      name: blue
      labels:
        name: app
        app: go
        color: blue
    spec:
      containers:
      - image: quay.io/awakia/go_server
        name: blue
        ports:
          - containerPort: 8080
