apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: green
  labels:
    name: app
    app: go
    color: green
spec:
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      name: green
      labels:
        name: app
        app: go
        color: green
    spec:
      containers:
      - image: quay.io/awakia/go_server
        name: green
        ports:
          - containerPort: 8080
